### ISSUE TITLE
Can't seem to deploy a cluster

### ISSUE THREAD

**Issue by dbbaskette** [sequenceiq/docker-cloudbreak#21]
Completed Credentials and it accepted it.   Then built a template which was accepted and an AMI was inserted into it ( ami-b4eb9adc).    Then I go to create a cluster and fill out the form.   The button is green at the bottom, but when I click it nothing happens.     No error at the top....the note from the previous step is still there (AWS template '51' was created successfully.     I am not sure where to even look to diagnose...the logs don't seem to be showing anything

**Comment by doktoric** [comment]
do you see any error in your browser console?

**Comment by dbbaskette** [comment]
"Error: blueprint is undefined
$scope.createCluster@http://localhost:3000/js/controllers/clusterController.js:58:1
$parseFunctionCall@http://localhost:3000/js/lib/angular.js:12158:1
ngEventHandler/</callback@http://localhost:3000/js/lib/angular.js:22645:28
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3000/js/lib/angular.js:14200:9
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/js/lib/angular.js:14298:11
ngEventHandler/<@http://localhost:3000/js/lib/angular.js:22650:17
n.event.dispatch@http://localhost:3000/js/lib/jquery-1.11.0.min.js:3:8010
n.event.add/r.handle@http://localhost:3000/js/lib/jquery-1.11.0.min.js:3:4743

**Comment by dbbaskette** [comment]
I am using the default blueprints and even tried creating my own....same error.

**Comment by dbbaskette** [comment]
Any updates on this? or perhaps a newer version to try?   I noticed significant differences in the hosted version and this one...3.1 vs 3.5 I think?  I tested all my inputs and everything works as expected on the hosted version, so its something specific to this version.

**Comment by lpuskas** [comment]
Yes, the docker image contains outdated versions, however upgrading to newer versions in the docker image would probably cause other issues.
There is a work in progress that will significantly change (ease) the deployment of the Cloudbreak, so till then we're ceasing the support for this version of the docker-cloudbreak. Please keep an eye on the project, we'll push the changes soon.

**Comment by doktoric** [comment]
you can use our deployer https://github.com/sequenceiq/cloudbreak-deployer 
This is a very easy way to deploy cloudbreak on any machine.
If you have any issue please let us know.
